### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by rsoika**
replaced inline code fragments with italic style to avoid broken layout on microprofile.io

See #222

### CODE REVIEW

**Comment by xstefank** [comment]
@rsoika we can't merge the PR without signed ECA. Can you take a look at this, please?

**Comment by rsoika** [comment]
Yes I have forgotten to sign it. What should I do? Can I create a new one?

**Comment by xstefank** [comment]
No, just sign the commit and force push this branch. This is what I usually do.

**Comment by rsoika** [comment]
Sorry I do not know how to do this. I was already on this page https://accounts.eclipse.org/legal/eca/validation/23377 and hit the 'revalidate' - but this seems not what is expected :-/

**Comment by xstefank** [comment]
@rsoika no worries. What you need to do is to log in/configure your local git with the same email that you've signed the ECA. Then just do `git commit -s `...`-am "message"` etc. The -s will sign the commit with your current configured email address. All commits in your PRs should be signed like this (but I think the check runs only for the latest one). And then force push this PR branch, or just do the same changes in different branch with a new commit (with -s) and a new PR. Hope this helps.

**Comment by rsoika** [comment]
I am really sorry for this chaos. I can't help myself. 
Please check this again: https://github.com/eclipse/microprofile-health/pull/249

You can see that I have a sign-off message in my commit. I do not understand the problem. I have done a similar change in the past to the config project here: https://github.com/eclipse/microprofile-config/pull/506

**Comment by xstefank** [comment]
@rsoika no worries, we all had to learn this once. Don't worry about this PR. If #249 is the same as this one, than just close this and let's move to #249 since that is already signed.

**Pull request closed without merging**
