### PR TITLE
Example prototype P2 API change for issue #43

### PR DESCRIPTION
**Pull request by starksm64**
This is just for review, DO NOT MERGE.

This is a second prototype of the API changes discussed in https://groups.google.com/forum/#!topic/microprofile/8l8AEmaduJ0
for issue #43 that also includes a change to the base Response object name to address a concern raised in https://groups.google.com/forum/#!topic/microprofile/zaLWMqFp7HA.

This version maintains the structure of the API that is similar to the javax.ws.rs.core.Response and javax.ws.rs.core.Response.ResponseBuilder.

Signed-off-by: Scott Stark <starksm64@gmail.com>

### CODE REVIEW

**Comment by heiko-braun** [comment]
Without going into details, this one get's my +1

**Comment by johnament** [comment]
with changes, I think this is the more feasible option.

**Comment by heiko-braun** [comment]
@johnament can you elaborate?

**Comment by johnament** [comment]
@heiko-braun The main issue right now is that you still have `HealthCheckResponse.named` as the entry point.

**Comment by heiko-braun** [comment]
@johnament For action we need a concrete proposal. What do like to see different and why? Is there any middle ground between the current proposal and your ideas?

**Comment by heiko-braun** [comment]
We've discussed both proposals based on the information available to the participants (github votes, ML comments) decided to move forward with PR #60.  Across all the comments we collected, there seem to be minor issues with each approach, but overall #60 seem to be the preferred one. Please don't see this a negative if #59 was your preference, but more as an invitation to iterate with us on the code base (read: your PR's are welcome).

**Pull request merged**
