### PR TITLE
Updated dependency versions

### PR DESCRIPTION
**Pull request by svenhaag**
Updated to the corresponding 2.0.2 dependency versions.

### CODE REVIEW

**Comment by xstefank** [comment]
@svenhaag thanks for this catch. However, you need to sign the commit with ECA https://www.eclipse.org/legal/ECA.php

**Comment by svenhaag** [comment]
@xstefank thanks. done.

**Comment by svenhaag** [comment]
New pull request with necessary signed-of, see: https://github.com/eclipse/microprofile-health/pull/189

**Comment by xstefank** [comment]
This can be closed then.

**Pull request closed without merging**
