### PR TITLE
First attempt on CDI managed health procedures

### PR DESCRIPTION
**Pull request by heiko-braun**
```
package org.eclipse.microprofile.health.tck.deployment;

[...]

public class CDIHealthCheck implements HealthCheckProcedure {
    @Override
    public HealthStatus execute() {
        return HealthStatus.named("CDI").up();
    }
}
```

### CODE REVIEW

**Comment by heiko-braun** [comment]
@Emily-Jiang Here's a non-pseudo code example for the CDI integration. It might as simple as implementing the `HealthCheckProcedure` interface to expose it as health check procedure.

**Comment by heiko-braun** [comment]
Actually I am thinking that we should rename  `HealthCheckProcedure ` to just `HealthCheck`

**Comment by kenfinnigan** [comment]
Does `HttpBinding` need to be in the API?

Wouldn't it be provided by an implementation?

**Comment by heiko-braun** [comment]
Yes, it would probably. Currently I am trying to get the basic scenarios with JAX-RS and CDI working  and adding `HttpBinding` to the API is the most simple to cover the `local` bindings scenario. `local` as in per deployment scope.

**Comment by Emily-Jiang** [comment]
@heiko-braun I am trying to understand which bits are provided by an implementation and which bits are provided by application developer. Is it correct to assume that the only implementation is HttpBinding class?

**Comment by Emily-Jiang** [comment]
@heiko-braun I am trying to understand this implementation. Can you please explain what needs to be provided by Runtime and what needs to be provided by apps? If the app provides the end point of /health, am I right to say the implementation is no-op.

**Comment by heiko-braun** [comment]
@Emily-Jiang We have choices and I am not certain about which approach to take at the moment:  The runtime provides the HTTP protocol adapter and the application provides the health check procedures. The alternative would be for the application to provide an HTTP adapter as well.

My first intention was a clean split between runtime (HTTP adapter) and application (health check procedure). What approach works best, depends on answers to the following questions:

- Do we want to support the EE7 deployment models? I.e. multiple deployments per runtime?
- Do we want to support the JAX-RS programming model or restrict this spec to the CDI only?

These questions matter because CDI is scoped per deployment and JAX-RS already has HTTP bindings that might interfere with a global `/health` HTTP binding. In general does the EE7 deployment model leads to conflicts with global HTTP bindings.

**Comment by Emily-Jiang** [comment]
I think the 1st release needs to be clear and small. We don't need to cover every scenario.

>a) The runtime provides the HTTP protocol adapter and the application provides the health check procedures.
This is clean and application developer knows what are expected.
>b) The alternative would be for the application to provide an HTTP adapter either exclusively or in addition to the global one. In the PR i create a distinction between global and local bindings to express this (see test cases)

What is the use case for this? What is the benefit to provide additional HTTP adapter? We need to think clearly about conflicting between the HTTP adapters.

> Do we want to support the EE7 deployment models? I.e. multiple deployments per runtime?

Yes
  >  Do we want to support the JAX-RS programming model or restrict this spec to the CDI only?
I would think the first release to restrict this spec to CDI only.

You can send email to the group to ask for more input.

**Pull request merged**
