### PR TITLE
Rebase to Swarm 2017.7.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by heiko-braun**

### CODE REVIEW

**Comment by kwsutter** [comment]
If we're going to update a dependency (Swarm) version, then please open the corresponding Contribution Questionnaire.  Reference Issue #5 for some details, and my discussion on our Google Group:  https://groups.google.com/forum/#!topic/microprofile/CSP0rPutSGw

**Comment by heiko-braun** [comment]
Thanks for the reminder  @kwsutter . According to your comments on #5 , it seems this has to be done before the first release. This means we don't have to do it right now while things are still in flux.

**Comment by heiko-braun** [comment]
@kwsutter Another question regarding the Contribution Questionnaire. Swarm is merely the reference implementation. It will not be included in the health 1.0 release. Do we still need a Contribution Questionnaire for it?

**Comment by kwsutter** [comment]
Yes, all 3rd party software usage needs to be registered with Eclipse.  Swarm sounds like it falls into the "works with" dependency classification, so those should be much easier to get through the process.

**Comment by kwsutter** [comment]
This merge broke the build.  This 2017.7.0-SNAPSHOT version doesn't seem to exist, so when I execute "mvn clean install", I get all kinds of errors.  When I revert back to 2017.4.0, everything builds cleanly again.  We should never merge code that causes errors like this.  I didn't Revert the changes since I'm assuming this is an easy clean up on your part.  But, if this still exists tomorrow, then I will Revert in order to clean this up.  Thanks.

**Comment by kwsutter** [comment]
Sorry, Heiko, had to revert this merge to allow me to verify my changes...  I have a PR #9 waiting to be merged.

**Comment by heiko-braun** [comment]
It's probably related to https://github.com/eclipse/microprofile-health/pull/6/files#diff-6d287b8ecd0440ec88de1c1b3e4187a6L103 . My bad, i'll fix it and provide another PR

**Pull request merged**
