### PR TITLE
Do not merge [issue #110] Wireformat `checks` property as object, not array, keyed…

### PR DESCRIPTION
**Pull request by xstefank**
… by check name

issue #110

### CODE REVIEW

**Comment by Emily-Jiang** [comment]
I suggest not to do this change as I don't see much benefit to introduce this change at all but cause more issues.

**Comment by xstefank** [comment]
@Emily-Jiang just for completeness - the unique names have been discussed in #34

**Comment by Emily-Jiang** [comment]
I have added a comment on that issue. Unless there is a business reason, I prefer not to do this as it will break old apps for no strong reason.

**Comment by antoinesd** [comment]
@Emily-Jiang one of the idea is to enforce uniqueness of check's name and to align on other practice around. Like it was discussed in #110, it is still possible to keep the old format for backward compatibility (with a flag for instance)

**Comment by Emily-Jiang** [comment]
I don't see any real benefit brought by this change except introducing breaking changes.

**Comment by xstefank** [comment]
Closing this PR. We will try this feature in the implementations first.

**Pull request closed without merging**
