### PR TITLE
Issue 222

### PR DESCRIPTION
**Pull request by rsoika**
changed README.adoc

### CODE REVIEW

**Comment by rsoika** [comment]
Yes, we already made the same kind of change to the readme file in the [microprofile-config project](https://microprofile.io/project/eclipse/microprofile-config).
You can see the result [here](https://microprofile.io/project/eclipse/microprofile-config) (see chapter 'Design' 1st line)
And when you compare it to the current layout from the microprofle-health page you see what I try to fix:
https://microprofile.io/project/eclipse/microprofile-health

**Comment by xstefank** [comment]
@rsoika perfect. Looks good from a functional perspective, just change the commit message and squash and I will merge this. Thanks.

**Comment by rsoika** [comment]
so, I hope everything is correct now.

**Comment by xstefank** [comment]
:) you have now 4 commits :) I would like you to squash them into one commit. This is just because it doesn't make sense to have one commit in history which is adding only one space. 

https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by rsoika** [comment]
Please let me know if this is what you expect.

**Comment by rafabene** [comment]
@rsoika I think those changes need to be placed after we merge/fix #210 and #248

**Comment by rsoika** [comment]
sorry I must give up here. I am unable to resolve the merge conflicts in my pull request. I did not succeed to squash the commits. Things get more and more worse. 

I am now absolutely frustrated. I am sorry that I stole your time.

**Comment by xstefank** [comment]
No need to apologize, these things happen. Just open the changes in new PR :)

**Pull request closed without merging**
